name: Deploy Gymso Site to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Save EC2 private key
      run: |
        echo "${{ secrets.EC2_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Upload files via SCP
      run: |
        scp -o StrictHostKeyChecking=no -i private_key.pem -r * ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/gymso-site

    - name: SSH and deploy to Apache folder
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo rm -rf /var/www/html/*
          sudo cp -r /tmp/gymso-site/* /var/www/html/
          sudo systemctl restart httpd
        EOF

